davidhalter/jedi-vim

jedi_vim.py
NeoComplete calls Jedi's `completefunc` frequently which clears Jedi's call signatures. This commit prevents command line call signatures from being cleared but doesn't affect the regular call signatures because they can errantly change the results of Jedi's completion function if not cleared.
=> Don't clear command line call signatures in completions()

AUTHORS.txt, README.rst, doc/jedi-vim.txt, jedi_vim.py
This allows to open a new split for "go to" in a vertical or horizontal split depending on the current window width.
=> Add 'winwidth' split option

AUTHORS.txt, autoload/jedi.vim
With default binding ("K") - `jedi#show_documentation()` behaves like a toggle. This behavior isn't replicated with a custom binding. This PR fixes that.
=> Set 'hide documentation' to jedi#documentation_command

after/syntax/python.vim
Use `containedin` instead with `jediFunction`.
This adopts any changes to the syntax definitions, instead of overwriting them.
I am not really sure how to test if it doesn't break anything.
Followup to #366, this time against master - the dev branch appears to be outdated..
=> Do not overwrite/re-define pythonString syntax regions

autoload/jedi.vim, jedi_vim.py
With less than `g:jedi#quickfix_window_height` entries in quickfix list,
this now only makes the window that large, effectively saving screen
space.
Maybe a new setting should be used for this instead, in case not having the same height always for the quickfix window might be an issue for someone?!
=> add_goto_window: pass len of list and use min()

jedi_vim.py
`echoerr` causes Vim to throw an error, but like the function name
indicates, this is only a warning.
=> Use "echohl WarningMsg" instead of "echoerr" in no_jedi_warning

jedi_vim.py
This makes it more useful, because module_path is usually(?) None, at least for `int`.
=> Use `desc_with_module` in "Builtin modules cannot be displayed" error

autoload/jedi.vim
Without this, the `<C-x><C-o>` triggered by jedi-vim would cause the first
match to be inserted (and selected).  When using completopt=longest,
this was less so an issue.
=> Fix popup-on-dot completion: use <C-p> to deselect the first entry

after/ftplugin/python/jedi.vim, after/syntax/python.vim, autoload/jedi.vim, doc/jedi-vim.txt, ftplugin/python/jedi.vim
This PR started with `"auto"` support for `g:jedi#force_py_version`, but then I've refactored it and improved the init handling altogether.
"auto" is meant to pick up the correct Python version from your Virtualenv etc.
Please let me know what you think about this PR altogether and I can then cleanup/squash the commits.
=> "auto" for force_py_version; optimize for Neovim; refactor init

README.rst, doc/jedi-vim.txt, ftplugin/python/jedi.vim, plugin/jedi.vim
The setting is also moved from "ftplugin" to "plugin", which allows for
easier customization, e.g. via a FileType plugin.
Ref: https://github.com/davidhalter/jedi-vim/issues/374#issuecomment-97621368
=> auto-config: set completeopt only if it's the default

after/ftplugin/python/jedi.vim
This deletes the selection (by going to visual mode, and "c"), and then
triggers the completion.
This is useful with e.g. UltiSnips, when you want to start completion
with an expanded snippet argument selected.
Ref: https://github.com/davidhalter/jedi-vim/pull/339#issuecomment-97612632
=> Select mode mapping for completion trigger

jedi_vim.py
Currently the command line call signature treats '\n' in a string as a literal newline (e.g. in the call signature for `print()`) and this just escapes the newline so it is printed as literal '\n'.
=> Escape newlines in call signatures with show_call_signatures=2

jedi_vim.py
I think this is less fragile altogether.
It uses Vim's `b:changedtick` and skips the `:normal! A ' hack.
=> Fix rename behaviour with empty cword; honor b:changedtick

jedi_vim.py
Commit 8016665 (PR #360) escaped the newlines in `text`, which requires to use the
escaped version with `text.index` and `len`, too.
This fixes the following error:
Traceback (most recent call last):
File "…/jedi/jedi_vim.py", line 110, in wrapper
return func(*args, **kwargs)
File "…/jedi/jedi_vim.py", line 414, in cmdline_call_signatures
left = text.index(params[index])
ValueError: substring not found
/cc @wilywampa (author of PR #360)
=> Fix ValueError with cmdline call signatures

README.rst
Fedora packages jedi-vim as the package name vim-jedi, this just adds that information under the installation section of the README
=> Add entry for Fedora Linux vim-jedi package

autoload/jedi.vim
This usually means that the `neovim` module is not installed, which
commonly happens in a virtualenv.
=> nvim: add a warning in case the auto-detected version is not functional

autoload/jedi.vim, plugin/jedi.vim
This command is meant to come in handy to debug problems with jedi-vim.
For now, it will display the Python version that jedi-vim is using.
=> Add JediDebugInfo command: display used Python version

autoload/jedi.vim
This is meant to be used in case you want to re-init the Python version
used by jedi-vim, without restarting Vim.
I had this laying around.. it might be better to just export
`s:init_python` as `jedi#init_python`?!
=> Add jedi#reinit_python

autoload/jedi.vim
This pull request fixes a global variable environment pollution. You can confirm the leak by `:echo key` or `:echo val` after opening an Python file.
=> make `key` and `val` script local

autoload/jedi.vim, doc/jedi-vim.txt, test/signatures.vim
Add `show_call_signatures_delay` option
This will use CursorHoldI instead of CursorMovedI for displaying call
signatures, with a delay of 500ms by default.
This greatly enhances the experience with slow call signatures while typing
(depending on how fast Jedi is for the given context).
Ref: #420.
It just came to my mind that this addresses (my) main issues with the call signatures, which can be nasty when `Jedi` is slow on some more complex context while typing.
=> Delayed call signatures

autoload/jedi.vim, doc/jedi-vim.txt, jedi_vim.py
I added a feature to use the tag stack instead of just the jump list. This is really convenient where you jump to a definition, then move around with all kinds of jumps to investigate whatever you jumped to, then can instantly jump back to the place `goto()` was called from with `<C-t>` instead of repeating `<C-o>` a bunch.
=> Add g:jedi#use_tag_stack feature for jedi#goto()

autoload/jedi.vim, test/signatures.vim
After `o`, call signatures should show up after `abs(`.
Followup of https://github.com/davidhalter/jedi-vim/pull/477.
=> Handle parenthesis with show_call_signatures' cache

autoload/jedi.vim, test/signatures.vim
The autocommands that display call signatures are reset globally any time `ftplugin/python/jedi.vim` is sourced so call signatures only work in the most recently loaded buffer. This change only resets autocommands in the current buffer. All of the `jedi_call_signatures` autocommands use `<buffer>` so that's what we want.
=> Fix signatures only working in a single buffer

AUTHORS.txt, autoload/jedi.vim
when I use `jedi-vim` and `neocomplete` a last option automatically select.
Please check past [issue](https://github.com/Shougo/neocomplete.vim/issues/485) to understand detail.
- https://github.com/Shougo/neocomplete.vim/issues/485
- https://github.com/Shougo/neocomplete.vim/issues/486
=> check "noselect" and "noinsert" before <C-p>

autoload/jedi.vim
With `nomagic` being set (not recommended, but might happen), the
pattern would not work.
This patch sets `\m` explicitly.
=> jedi#smart_auto_mappings: use `\m` with `search()` for `magic`

jedi_vim.py
The cursor would change to something else once in the insert mode. If
the new name was longer than the old one, the Parser couldn't get
the stmt at the wrong cursor position, thus rename failed.
Now save the cursor position before entering the insert mode. Then pass
the saved position to the 2nd call to the rename().
=> Fix: rename() kept wrong cursor position #545

jedi_vim.py
The whole int/string conversion with `vim.eval` is confusing enough, use
a boolean for `is_eval`.
=> Clarify arguments with _catch_exception

jedi_vim.py
Cast integers with vim_eval
This makes it clearer/more strict altogether and is future-proof in the
sense that `vim.eval` might return integers for ints in Vim after all.
See #553 for a very noisy discussion of what led to this.
Although it might be a regression in neovim-python after all it is good
to be on the save side.
The bonus here is that we get "notified" in case of a option that is
expected to be a int is a string - although that might also cause some
weird issues in case someone uses "yes" instead of 1 (?!).
Fixes https://github.com/davidhalter/jedi-vim/issues/553.
=> Cast integers with vim_eval

autoload/jedi.vim
I got this error after I updated my local copy of jedi-vim to
'e8b88f0161ef2adabda97d4e083585a3becdcb53':
```
Error detected while processing function jedi#clear_call_signatures:
line    6:
E492: Not an editor command:     jedi_vim.clear_call_signatures()
```
The error below happened because 'PythonJedi' was missing before
jedi_vim.clear_call_signatures() in autoload/jedi.vim.
I put back 'PythonJedi' and it solved the issue.
=> Bug fix: E492: Not an editor command: jedi_vim.clear_call_signatures()

AUTHORS.txt, ftplugin/python/jedi.vim
I was testing a plugin (setting/changing `filetype` a lot) and noticed the `autocmd` for closing preview windows was piling up.  As far as I can tell, there isn't a need to rerun the ftplugin after it's already setup.
=> Prevent redefinition of InsertLeave in buffers

jedi_vim.py
This was meant as a hack to make the jumplist work (7520290), but it
works without it.  Maybe the underlying code to go to the definition has
been changed/improved.
Tested both in Vim (7.4.2143) and Neovim.
=> Do not set the '`' mark in goto

autoload/health/jedi.vim, autoload/jedi.vim
See https://github.com/neovim/neovim/blob/master/runtime/doc/pi_health.txt.
Example output for me:
```
…
health#jedi#check
================================================================================
Using Python version: 3
- sys.version: 3.5.2 (default, Jun 28 2016, 08:46:01), [GCC 6.1.1 20160602]
- site module: /usr/lib/python3.5/site.py
Jedi path: /home/user/.dotfiles/vim/neobundles/jedi/jedi/jedi/__init__.py
Jedi version: 0.10.0
jedi-vim git version: 0.8.0-42-g7c7c376-dirty
jedi git submodule status: +be2a97cd36ce1b7d6f587ef122efc3433b1e8ae2 jedi (v0.9.0-533-gbe2a97c)
…
```
=> Hook into Neovim's :CheckHealth with jedi#debug_info

AUTHORS.txt, autoload/jedi.vim
Syntax highlighting on chars in g:jedi#call_signature_escape may
break the funciton parameter hint from jedi-vim. Change its default
value to non python syntax symbols to reduce chance of collision
=> Change default g:jedi#call_signature_escape to avoid collision

jedi_vim.py
Fixes https://github.com/davidhalter/jedi-vim/issues/641.
=> Use `re.escape` for the `g:jedi#call_signature_escape` setting

jedi_vim.py
It became obsolete in 794af5b, but setting it was not removed then.
=> Remove obsolete s:jedi_changedtick and fix style

plugin/jedi.vim
=> Fix default of jedi#auto_vim_configuration back to 1

.travis.yml, Makefile
This allows for calling them easily locally.
Downside: puts installation of `vint` into the `script` part of the Travis job.
=> Move Travis targets to Makefile

initialize.py
Do not keep adding jedi_vim_path to sys.path.
=> initialize.py: handle reloading of the plugin

autoload/jedi.vim
I am using https://github.com/Rykka/riv.vim as the rst plugin, it fold rst file automatically.  
This also affects the `__doc__` buffer of python, because its filetype is rst.  
I don't think we need fold in `__doc__`, because it's usually short.
=> Fix unwanted fold in __doc__

autoload/jedi.vim, doc/jedi-vim.txt
It would be ignored already with completions_enabled=0.
This documents it and makes the default follow it.
=> popup_on_dot: document that it needs completions_enabled

autoload/jedi.vim
This is meant to help in case of issues where the Python initialization
fails (https://github.com/davidhalter/jedi-vim/issues/726#issue-248054145),
so that `JediDebuginfo` can still provide some more information.
=> Define PythonJedi command always

.gitmodules, autoload/jedi.vim, pythonx/jedi_vim.py
Move jedi_vim.py and the jedi submodule into pythonx, which gets added
to Vim's internal sys.path.  While jedi cannot be imported directly from
there, it still makes sense for consistency.
=> Use Vim's pythonx mechanism

autoload/jedi.vim, pythonx/jedi_vim_debug.py
This allows vimlparser to parse the vim file again, and it is more
convenient to have it in a real Python file anyway.
Small refactoring and minor text changes included.
=> Move Python code for jedi#debug_info into pythonx

README.rst
Ref: https://github.com/davidhalter/jedi/issues/910#issuecomment-322731875
=> README: improve FAQ for slowness, add deoplete-jedi

.gitmodules, .travis.yml, autoload/jedi.vim, conftest.py, pythonx/jedi_vim.py, test/completions.vim, test/goto.vim, test/pyimport.vim, test/signatures.vim
I fixed the tests and re-enabled them to travis-ci.
After that I was finally able to update to `jedi` 0.11.0. `parso` is now also a submodule.
There's quite a lot of changes, but it's actually not that bad. The test changes are just fixes, you can ignore those (because they didn't pass before).
The `jedi_vim.py` changes are not as big as it looks. It's mostly removing things that were deprecated in Jedi a while ago and a big dedent.
BTW: I also removed the call signature problems where param was used everywhere. I don't like that change, but the jedi API is not good enough there.
=> Fix tests & update jedi to 0.11.0

pythonx/jedi_vim_debug.py
Hi. I found CheckHealth bug in neovim.
CheckHealth calls `display_debug_info()`.
However, error occured when loading `jedi_vim.jedi.Script('')._evaluator.sys_path`,
because `Evaluator.sys_path` is unavailable variable.
=> fix: CheckHealth doesn't work in neovim

README.rst
Change the link on readme about stackoverflow to see the posts tagged with "jedi-vim".
=> Readme: fix stackoverflow link (#782)

README.rst
Hi !
As @zwidny noticed in #748, there is no description in the README for Vundle install type.
This pr just adds the missing description.
Would not it be better to add a dedicated subsection for Vundle install type ?
=> [IMP] README.rst - Add a description for Vundle installation.

pythonx/jedi_vim.py
Unlisted buffers might come e.g. from `set viminfo+=%`, and Jedi would
crash on them.
This could additionally check for them to be readable, but this should
be handled in Jedi itself anyway.
=> get_script: additional_dynamic_modules: add only listed buffers

autoload/jedi.vim
Just check for `has('python3')` / `has('python')`.
Fixes https://github.com/davidhalter/jedi-vim/commit/72a2643f7c0e6f895b7bf61d2b180c42b143aa7b#r28922063.
=> Fix s:init_python

autoload/jedi.vim
Uses `repr` for SyntaxErrors.
Related: https://github.com/neovim/python-client/pull/221
=> jedi#setup_python_imports: better SyntaxError handling

pythonx/jedi_vim.py, test/goto.vim
Fixes #802.
One test was changed. Now it only follows imports. IMO this is what users want. The old behavior is just very random and does sometimes something completely different than other times.
=> Use the official Jedi goto API instead of multiple calls

autoload/jedi.vim
It was removed previously, since it now refers to the environment being
used.
This brings it back for now.
There could be a separate var for it later, and/or it needs changes
later (or rather the environment needs a new variable name, since it
should refer to the executable really) - but this is good for now I think.
Fixes https://github.com/davidhalter/jedi-vim/issues/833
=> s:init_python: handle g:jedi#force_py_version again

pythonx/jedi_vim.py
I am seeing `p` twice for os.path.dirname, which seems to come from
Lib/posixpath.py and Lib/ntpath.py, as can be seen with `os.path.join`,
where I still see two with this patch:
```
(path, *paths)
import os   (a, *p)
os.path.join()
```
btw: I had a hard time (i.e. failed) to get the filename information for the underlying definitions.
I think it might be useful to add additional information to the call signature in case there are multiple signatures and they are coming from different files/modules maybe?
=> Skip duplicate call signatures

autoload/jedi.vim, pythonx/jedi_vim.py, pythonx/jedi_vim_debug.py
This is taken out of https://github.com/davidhalter/jedi-vim/pull/836.
=> Improve JediDebugInfo for envs

.travis.yml, Makefile, test/completions.vim, test/signatures.vim
This will allow us to get coverage via its Python subprocess then.
Includes #862 for setting `VSPEC_VIM`.
=> Test with Neovim also

.coveragerc, .gitignore, .travis.yml, Makefile, conftest.py, test/documentation.vim, test/vimrc
TODO:
Includes/rebased on #864 for now.
=> Report coverage

Makefile, autoload/jedi.vim
When being initialized via ftplugin `set shortmess+=F` (default in
Neovim by now) causes the additional information (the full traceback) to
be silenced.
This patch uses `:unsilent` to always display it.
Ref: https://github.com/neovim/neovim/issues/8675
=> Fix displaying of error information with shortmess+=F

.coveragerc
Fixes https://github.com/neovim/python-client/issues/354
=> .coveragerc: concurrency = greenlet

AUTHORS.txt, doc/jedi-vim.txt
Looks like this was introduced in 439e50e9 (2015-06-21). Apparently didn't bother anyone for 3 years, but might as well fix it!
=> Fixes incorrect documentation

README.rst
As per the author's comment here, Python 2.6 is no longer supported. https://github.com/davidhalter/jedi-vim/issues/866#issuecomment-409852888
=> Update Python version in README

autoload/jedi.vim
Parso's cache can be cleaned from Jedi now.
=> Fix `:JediClearCache!`

README.rst, autoload/jedi.vim, doc/jedi-vim.txt, ftplugin/python/jedi.vim, plugin/jedi.vim, pythonx/jedi_vim.py, test/test_integration.py, test/vspec/goto.vim, test/vspec/signatures.vim
(If there's a module_path, which most will have)
This change is still backwards compatible and can be used with older Jedi
versions (<0.14.0).
We can merge this now or later. IMO it's good to merge now, because it won't really change the behavior AFAIK.
=> With typeshed coming to Jedi, builtin modules should be displayed

autoload/jedi.vim, ftplugin/python/jedi.vim, pythonx/jedi_vim.py
Pretty messy still (at least from the code), but some benefits:
- keeps definitions around until some text is changed (or the quickfix window is closed)
- keeps the qf window open on winleave
- uses `:cwindow` and no `:cclose` for better qf behavior in general, also gets rid of redraw! etc
- adds `p` for preview, although I find (mapped) `:cnext` etc better
- stores the actual matchids with the window
TODO:
=> [RFC] Revisit usage highlighting

pythonx/jedi_vim.py
Closes https://github.com/davidhalter/jedi-vim/issues/948.
=> completions: skip docstr without preview, handle exceptions

autoload/jedi.vim, test/vspec/signatures.vim
Without this it would not redraw properly when moving left within `print(…)` - see the test.
=> Fix invalidating cache with `jedi#show_call_signatures`

.github/FUNDING.yml
I have been accepted into the Github sponsorship program. I feel like you @blueyed could do that as well, so we could have both our names there.
If you don't like adding the button there, I'm fine with just leaving it out. I have it up on the Jedi repository.
In general I just want to try if this works and if there is going to be income generated through the button.
I don't think there will be a lot of money, so it probably doesn't even make sense to share it at this point. But if it happens to be more than a 200? dollars a month we should probably talk about it.
=> Add a funding button to github

pythonx/jedi_vim.py, test/vspec/documentation.vim
The documentation test fails with newer Jedi, this is for investigating it.
```
________________ test_integration[test/vspec/documentation.vim] ________________
test/vspec/documentation.vim failed:
"__doc__" [New File]
not ok 1 - documentation docstrings simple
5 buffers wiped out
ok 2 - documentation docstrings no documentation
1..2
```
TODO:
test/vspec/documentation.vim failed:
not found in 'runtimepath': "ftdetect/*.vim"
not ok 1 - documentation docstrings simple
5 buffers wiped out
ok 2 - documentation docstrings no documentation
1..2
=> minor: rewrite/expand show_documentation

README.rst, autoload/jedi.vim, ftplugin/python/jedi.vim
It basically allows to give a warning when '1' is used / set explicitly, and
the 'conceal' feature is not available.
Also defaulting to '2' (cmdline mode) then seems better than not using
it.
This is just some minor clean up before
https://github.com/davidhalter/jedi-vim/pull/652.
=> show_call_signatures: doc, default to 2 without 'conceal'

.travis.yml, test/vspec/jedi_debug_info.vim
=> tests: cover jedi_debug_info

pythonx/jedi_vim.py
Seen with `<Definition name='key', description='param key'>` (using
usages on an function argument) [1].
1: https://github.com/pytest-dev/py/blob/2b6bd2925/py/_vendored_packages/iniconfig.py#L32-L33
=> show_goto_multi_results: handle `full_name=None`

autoload/jedi.vim, pythonx/jedi_vim.py
Without this it would not go there with an already open qf window, and
would go to an unexpected buffer line instead of selecting the entry.
This is a follow-up to b689409, where it was decided that it should
always require the user to select an entry.
An exception is when the same usages are used again: then it will select
the nearest/current entry only (via ":cc").
=> Fix jedi#add_goto_window: use :copen to go to the qf window always

autoload/jedi.vim
In particular it should not try to import `jedi_vim_debug` during error
handling "unprotected", which might hide the real error on Python 2 at
least.
Ref: https://github.com/davidhalter/jedi-vim/issues/998#issuecomment-592305240
=> Improve/harden jedi#setup_python_imports

doc/jedi-vim.txt
’ character is not rendered nicely when LANG is not set.
=> doc/jedi-vim.txt: fix apostrophe

.github/workflows/ci.yml, .travis.yml, README.rst, autoload/jedi.vim, doc/jedi-vim.txt, plugin/jedi.vim, pythonx/jedi_vim.py, pythonx/jedi_vim_debug.py, test/vspec/choose-venv.vim, test/vspec/documentation.vim, test/vspec/goto.vim, test/vspec/pyimport.vim
- Removed all usages of deprecated functions in Jedi
- Reworked environment support. We are using `jedi.Project` now to manage environment paths (This might make parts of #836 not necessary)
- Added `:JediChooseEnvironment` (which displays a list of environments that a user can choose)
- Added a for now undocumented `:JediLoadProject`, which might need some changes to Jedi to properly work like I want it to.
Still thinking about implementing refactorings.
Would be interested in @blueyed's thoughts about these changes.
=> Use the new Jedi API

AUTHORS.txt, pythonx/jedi_vim.py
Use helper function relpath() instead of os.path.relpath()
to address issue #1044 ("path is on mount %r, start on mount %r" exception thrown
on Windows if Python and jedi-vim are installed on different drives)
=> Use helper function relpath() instead of os.path.relpath()

doc/jedi-vim.txt, pythonx/jedi_vim.py
The buffer-local variable `b:jedi_environment_path` was added to jedi-vim to allow the user to override the global variable `g:jedi#environment_path` in the current buffer (useful to set a different virtualenv or Python version in the current buffer).
=> The buffer-local variable `b:jedi_environment_path`

README.rst
I searched for half an hour, why in :checkhealth of nvim, python 2 virtual environment is not shown, until I realized, that py2 is not supported by jedi itself.
So I think it's a good idea to mention in Readme that python 2 is not supported anymore. Maybe saves someones time.
=> doc: Add hint about python 2 support

AUTHORS.txt, autoload/jedi.vim
I think I found a small bug in the default settings. The default setting for `added_sys_path` is sting quoted twice which leads to the value of `g:jedi#added_sys_path` beeing the string `"[]"` instead of an empty list.
Executing `python3 print(jedi_vim.get_project().added_sys_path)` returns `['[', ']']` instead of an empty list.
A results, for example, is that `:checkhealth` crashes when `g:jedi#added_sys_path` is actually set.
```
:let g:jedi#added_sys_path = ["../test"]
:checkhealth
health#jedi#check
========================================================================
- ERROR: Failed to run healthcheck for "jedi" plugin. Exception:
function health#check[21]..health#jedi#check[2]..jedi#debug_info, line 64
Vim(if):E691: Can only compare List with List
```
I'm not too familiar with …
=> Fix added_sys_path default setting

pythonx/jedi_vim.py
- the common case is having an exception here (with no buffer setting),
which results in the exception handler always
- vim_eval has overhead, especially with Neovim, so the less calls the
better
This patch changes it to query the `b:` dict, using the (always
set/initialized) global setting as the default.
Ref: #1059 /cc @jamescherti (just for information)
=> get_project: simplify getting b:jedi_environment_path override

AUTHORS.txt, autoload/jedi.vim, doc/jedi-vim.txt, pythonx/jedi_vim.py
This pull request adds an option to enable/disable case insensitive completion (the Jedi setting: `jedi.settings.case_insensitive_completion`).
It adds the following options to jedi-vim:
- Global option: `g:jedi#case_insensitive_completion`
- Buffer-local option: `b:jedi_case_insensitive_completion`
Values:
- 0 to disable case insensitive completion.
- 1 to enable case insensitive completion (default).
=> Add option to enable/disable case insensitive completion

README.rst, autoload/jedi.vim, doc/jedi-vim.txt, ftplugin/python/jedi.vim, pythonx/jedi_vim.py
This pull request adds the key mapping `<Leader>R` (upper case R) to rename variables/functions/classes without deleting the word under the cursor:
- **`<Leader>R` in Normal mode:** Jedi-vim keeps the word under the cursor, moves the cursor to the end of the word, and puts Vim in insert mode, where the user is expected to enter the new variable name.
- **`<Leader>R` in Visual mode:** Use the selected text as the default answer to the prompt.
**Bug fix:** This pull request also adds the support for `set selection=exclusive` to the function `rename_visual()`
=> Add a keyboard mapping to rename  variables/functions/classes without deleting the word under the cursor

README.rst
Hi there! I was reading the installation instructions and requirements and saw that Python 2.7 was required, so I went ahead and installed jedi-vim. However, upon starting vim next, I learned that Python 2.7 was no longer supported. This PR just removes Python 2.7 from the requirements so that the requirements are clearer/up-to-date. If I'm missing something and Python 2.7 is still required, please feel free to close this PR.
=> Remove mention of Python 2.7 support in installation instructions

README.rst
Add information for Neovim that the python package `pynvim` is needed for a working python environment inside `nvim`.
Also so provide command needed to check that the environment setup is functional.
=> Add Neovim Installation Requirements
