conftest.py

There is still something odd (probably), but this looks a lot better on the eyes at least.. ;)

Improve tests: use pytest.fail

---

autoload/jedi.vim
doc/jedi-vim.txt

Add max_doc_height setting

---

autoload/jedi.vim
ftplugin/python/jedi.vim
jedi_vim.py

This should fix #362 and other (non-reported) issues.

Fix rename

---

README.rst
autoload/jedi.vim
doc/jedi-vim.txt
ftplugin/python/jedi.vim
jedi_vim.py

Based on discussions in https://github.com/davidhalter/jedi/issues/570.
Waiting for support in Jedi, but uses what's available currently for now.

Better goto functionality

---

autoload/jedi.vim

Change to address https://github.com/davidhalter/jedi-vim/issues/421. Use `winwidth` commands and geometry/math to find first column of current window instead of `wincmd`/`'eventignore'`/`undojoin` ugliness.

Find first column using winwidth instead of wincmds/undojoin

---

README.rst
autoload/jedi.vim
doc/jedi-vim.txt
test/goto.vim
test/pyimport.vim

Ref: https://github.com/davidhalter/jedi-vim/issues/408#issuecomment-101997691

Use use_tabs_not_buffers=0 by default

---

jedi_vim.py

Ref: https://github.com/davidhalter/jedi-vim/issues/460

Pass ImportError to no_jedi_warning and display it there

---

autoload/jedi.vim

Followup to e241cf87fdccaa4f5eec48d4e4063920f2dfddea.
Ref: https://github.com/davidhalter/jedi-vim/pull/420.
Ref: https://github.com/davidhalter/jedi-vim/pull/475#issuecomment-149013542.

Invalidate `show_call_signatures_delay` on InsertEnter

---

jedi_vim.py

Use a NamedTemporaryFile context manager, which removes the temporary
file again, and use it as the only entry for the 'tags' setting to
improve lookup performance.
/cc @wilywampa

Improve use_tag_stack-hack: use context managers, short 'tags'

---

conftest.py
jedi_vim.py

Fixes Python 2.6 compatibility issues with `str.format()`

---

autoload/jedi.vim
initialize.py
jedi_vim.py

This will provide more information in case of errors.

Improve error messages during init

---

jedi_vim.py

Ref: https://github.com/davidhalter/jedi-vim/issues/553

minor: improve error msg with invalid use_splits_not_buffers setting

---

initialize.py

Ref: https://github.com/davidhalter/jedi-vim/issues/574

Make initialize.py more robust

---

ftplugin/python/jedi.vim

Fix preview autocmd being cleared for all buffers

---

README.rst
jedi_vim.py

Fixes https://github.com/davidhalter/jedi-vim/issues/560.
This PR also improves the README.

Improve error msg when the jedi submodule fails to load

---

doc/jedi-vim.txt

Fix doc link

---

autoload/jedi.vim
plugin/jedi.vim

This can be used to work around issues like
https://github.com/davidhalter/jedi/issues/784.
Not sure about the interface and/or the methods it calls - to be discussed.

Add JediClearCache command

---

.travis.yml
after/ftplugin/python/jedi.vim
autoload/jedi.vim
ftplugin/python/jedi.vim
plugin/jedi.vim

This also adds a augroup for `jedi#add_goto_window`.

Style fixes (via vint)

---

autoload/jedi.vim

Fixes https://github.com/davidhalter/jedi-vim/issues/663.

Fix return value of jedi#complete_opened

---

autoload/jedi.vim
jedi_vim.py

Fixes https://github.com/davidhalter/jedi-vim/issues/675.

Make jedi#debug_info more robust

---

README.rst

📄 Make Travis badge unpixely

---

.github/ISSUE_TEMPLATE.md

This modifies the issue template that GitHub uses.

Clarify how to use minimal.vimrc to report issues

---

autoload/jedi.vim

Don't try to highlight rst indented sections as python.

---

README.rst

Make sure to return to the original directory after git clone

Enhance example installation command

---

autoload/jedi.vim
plugin/jedi.vim
pythonx/jedi_vim.py
pythonx/jedi_vim_debug.py

See the individual commits.
TODO:

init: improve handling of import errors

---

Makefile

Upgrade jedi to 0.12.1, forgot to upgrade it when upgrading parso

---

conftest.py
test/completions.vim
test/completions_disabled.vim
test/documentation.vim
test/goto.vim
test/pyimport.vim
test/signatures.vim

This fixes some tests to make it work with the newer version.

Upgrade vim-vspec to 1.8.1

---

ftplugin/python/jedi.vim

Fixes https://github.com/davidhalter/jedi-vim/issues/882.

ftplugin: do not duplicate jedi_usages autocommands

---

autoload/jedi.vim
doc/jedi-vim.txt
test/vspec/completions.vim

Ref: https://github.com/davidhalter/jedi-vim/issues/568

Disable smart_auto_mappings by default

---

pythonx/jedi_vim_debug.py

This helps with bug reports in general.

display_debug_info: add global sys.executable

---

autoload/jedi.vim

Ref: https://github.com/davidhalter/jedi-vim/issues/949

jedi#debug_info: escape script path for "git"

---

autoload/jedi.vim

Ref: https://github.com/davidhalter/jedi-vim/issues/953

debug info: catch any errors with PythonJedi commands

---

pythonx/jedi_vim.py

This is helpful information to have in case of errors.

VimError: include throwpoint

---

README.rst
doc/jedi-vim.txt

Document the goto_stubs mapping <leader>s

---

pythonx/jedi_vim.py

Fix "goto" with multiple results

---

.github/workflows/ci.yml
README.rst
test/vspec/signatures.vim

@blueyed brought up a few small issues that I've fixed here.

Some fixes

---

doc/jedi-vim.txt
pythonx/jedi_vim.py

This pull request adds the buffer-local option `b:jedi_added_sys_path` that can be used to add additional sys_path.

Add the buffer-local option 'b:jedi_added_sys_path'

---

doc/jedi-vim.txt
ftplugin/python/jedi.vim
plugin/jedi.vim
pythonx/jedi_vim.py

prefer popup over preview window
